server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: springcloudorder
    url: jdbc:mysql:///ordersystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true